// Canonical list of event type strings used throughout the system

export const EventTypes = {
  // Movement
  PLAYER_MOVED: "PLAYER_MOVED",
  NPC_MOVED: "NPC_MOVED",

  // Combat
  ATTACK_ATTEMPT: "ATTACK_ATTEMPT",
  DAMAGE_APPLIED: "DAMAGE_APPLIED",
  HEAL_APPLIED: "HEAL_APPLIED",
  ENTITY_DIED: "ENTITY_DIED",
  NPC_ATTACKED: "NPC_ATTACKED",

  // Magic
  CAST_SPELL: "CAST_SPELL",
  MANA_CHANGED: "MANA_CHANGED",

  // Items & Inventory
  ITEM_PICKED_UP: "ITEM_PICKED_UP",
  ITEM_DROPPED: "ITEM_DROPPED",
  USE_ITEM: "USE_ITEM",
  EQUIP_ITEM: "EQUIP_ITEM",
  UNEQUIP_ITEM: "UNEQUIP_ITEM",
  ITEM_EQUIPPED: "ITEM_EQUIPPED",
  ITEM_UNEQUIPPED: "ITEM_UNEQUIPPED",

  // Economy
  GOLD_CHANGED: "GOLD_CHANGED",
  BUY_ITEM: "BUY_ITEM",
  SELL_ITEM: "SELL_ITEM",
  MERCHANT_STOCK_CHANGED: "MERCHANT_STOCK_CHANGED",

  // Crafting & Runes
  CRAFT_ITEM: "CRAFT_ITEM",
  ENGRAVE_RUNE: "ENGRAVE_RUNE",
  RUNE_ENGRAVED: "RUNE_ENGRAVED",

  // Effects
  EFFECT_APPLIED: "EFFECT_APPLIED",
  EFFECT_EXPIRED: "EFFECT_EXPIRED",

  // Progression
  XP_GAINED: "XP_GAINED",
  LEVEL_UP: "LEVEL_UP",
  CHARACTER_UPDATED: "CHARACTER_UPDATED",

  // Reputation & Factions
  REPUTATION_CHANGED: "REPUTATION_CHANGED",
  STANDING_CHANGED: "STANDING_CHANGED",

  // Quests
  QUEST_STARTED: "QUEST_STARTED",
  QUEST_PROGRESS: "QUEST_PROGRESS",
  QUEST_COMPLETED: "QUEST_COMPLETED",

  // Dialogue
  DIALOGUE_STARTED: "DIALOGUE_STARTED",
  DIALOGUE_ENDED: "DIALOGUE_ENDED",

  // Visibility
  VISIBILITY_UPDATED: "VISIBILITY_UPDATED"
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]
